[package]
name = "bevy_auto_plugin_proc_macros"
version = "0.2.1"
authors = ["Brett Striker <strikeforcezero@gmail.com>"]
repository = "https://github.com/StrikeForceZero/bevy_auto_plugin/crates/bevy_auto_plugin_proc_macros"
license = "MIT OR Apache-2.0"
description = "proc macros for bevy_auto_plugin"
edition = "2024"
publish = true

[lib]
proc-macro = true

[features]
log_plugin_build = ["bevy_auto_plugin_shared/log_plugin_build"]
missing_auto_plugin_check = ["bevy_auto_plugin_shared/missing_auto_plugin_check"]
missing_auto_plugin_is_compile_error = ["bevy_auto_plugin_shared/missing_auto_plugin_check"]
missing_auto_plugin_is_error = ["bevy_auto_plugin_shared/missing_auto_plugin_check", "bevy_auto_plugin_shared/log"]
missing_auto_plugin_is_warning = ["bevy_auto_plugin_shared/missing_auto_plugin_check", "bevy_auto_plugin_shared/log"]

[dependencies]
bevy_auto_plugin_shared = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
