[package]
name = "bevy_auto_plugin"
version = "0.2.1"
authors = ["Brett Striker <strikeforcezero@gmail.com>"]
repository = "https://github.com/StrikeForceZero/bevy_auto_plugin"
license = "MIT OR Apache-2.0"
description = "Procedural macros to simplify and streamline the creation of Bevy plugins by automating the registration of types, initialization of resources, and addition of events"
edition = "2024"
rust-version = "1.88"
publish = true

[features]
default = []
# optional extras
log_plugin_build = ["bevy_auto_plugin_proc_macros/log_plugin_build"]
missing_auto_plugin_is_compile_error = ["bevy_auto_plugin_proc_macros/missing_auto_plugin_is_compile_error"]
missing_auto_plugin_is_error = ["bevy_auto_plugin_proc_macros/missing_auto_plugin_is_error"]
missing_auto_plugin_is_warning = ["bevy_auto_plugin_proc_macros/missing_auto_plugin_is_warning"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bevy_auto_plugin_shared = { version = "0.2.1", path = "crates/bevy_auto_plugin_shared" }
bevy_auto_plugin_proc_macros = { version = "0.2.1", path = "crates/bevy_auto_plugin_proc_macros" }
bevy = { version = "0.16", default-features = false, features = ["bevy_state"] }
bevy_app = { version = "0.16", default-features = false }
bevy_state = { version = "0.16" }
bevy_reflect = { version = "0.16" }
bevy_internal = { version = "0.16" }
bevy_ecs = { version = "0.16" }
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
thiserror = "2"
log = "0.4"

[dependencies]
bevy_auto_plugin_proc_macros = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
bevy_app = { workspace = true }
bevy_reflect = { workspace = true }
bevy_ecs = { workspace = true }
bevy_state = { workspace = true }
internal_test_util = { path = "crates/internal_test_util" }
trybuild = "1.0"
log = { workspace = true }
