[package]
name = "bevy_auto_plugin_macros"
version = "0.0.0"
authors = ["Brett Striker <strikeforcezero@gmail.com>"]
edition = "2021"

[features]
missing_auto_plugin_is_compile_error = ["proc_macros/missing_auto_plugin_is_compile_error"]
missing_auto_plugin_is_error = ["proc_macros/missing_auto_plugin_is_error"]
missing_auto_plugin_is_warning = ["proc_macros/missing_auto_plugin_is_warning"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
proc_macros = { path = "crates/proc_macros" }
bevy = { version = "0.15" }
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
thiserror = "2"
log = "0.4"

[dependencies]
proc_macros = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
internal_test_util = { path = "crates/internal_test_util" }
trybuild = "1.0"