[package]
name = "bevy_auto_plugin"
version = "0.3.0"
authors = ["Brett Striker <strikeforcezero@gmail.com>"]
repository = "https://github.com/StrikeForceZero/bevy_auto_plugin"
license = "MIT OR Apache-2.0"
description = "Procedural macros to simplify and streamline the creation of Bevy plugins by automating the registration of types, initialization of resources, and addition of events"
edition = "2024"
rust-version = "1.88"
publish = true

[features]
default = [
    "lang_server_noop"
]
# DEPRECATED - Only exists for migration purposes
legacy_path_param = ["bevy_auto_plugin_proc_macros/legacy_path_param"]
inventory = ["bevy_auto_plugin_shared/inventory"]
# optional extras
log_plugin_build = ["bevy_auto_plugin_proc_macros/log_plugin_build"]
missing_auto_plugin_is_compile_error = ["bevy_auto_plugin_proc_macros/missing_auto_plugin_is_compile_error"]
missing_auto_plugin_is_error = ["bevy_auto_plugin_proc_macros/missing_auto_plugin_is_error"]
missing_auto_plugin_is_warning = ["bevy_auto_plugin_proc_macros/missing_auto_plugin_is_warning"]
# This "hack" will check the current executable from the env
#   when exe file_stem (without extension) != `rustc` - allows the macros to act like a no-op on failure to resolve `local_file`
#   required for use in many IDE's until these stubs get fully implemented: https://github.com/rust-lang/rust/blob/4e973370053a5fe87ee96d43c506623e9bd1eb9d/src/tools/rust-analyzer/crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs#L144-L147
lang_server_noop = ["bevy_auto_plugin_proc_macros/lang_server_noop"]

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bevy_auto_plugin_shared = { version = "0.3.0", path = "crates/bevy_auto_plugin_shared" }
bevy_auto_plugin_proc_macros = { version = "0.3.0", path = "crates/bevy_auto_plugin_proc_macros" }
bevy = { version = "0.16", default-features = false, features = ["bevy_state"] }
bevy_app = { version = "0.16", default-features = false }
bevy_log = { version = "0.16", default-features = false }
bevy_state = { version = "0.16" }
bevy_reflect = { version = "0.16" }
bevy_internal = { version = "0.16" }
bevy_ecs = { version = "0.16" }
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
thiserror = "2"
log = "0.4"
smart-default = { version = "0.7" }
darling = "0.21"
inventory = "0.3"
linkme = "0.3"
ctor = { version = "0.4" }

[dependencies]
bevy_auto_plugin_proc_macros = { workspace = true }
bevy_auto_plugin_shared = { workspace = true }

[dev-dependencies]
# required for doc tests
bevy = { workspace = true }
bevy_app = { workspace = true }
bevy_reflect = { workspace = true }
bevy_ecs = { workspace = true }
bevy_state = { workspace = true }
internal_test_util = { path = "crates/internal_test_util" }
trybuild = "1.0"
# used in feature tests
log = { workspace = true }