name: CI

on:
  # Trigger the workflow on push and pull requests to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings
  RUSTDOCFLAGS: --deny warnings

jobs:
  # ---------- native targets ----------
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-set: [ default, missing_auto_plugin_is_compile_error, legacy_path_param, inventory ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: |
          echo "Testing with features: ${{ matrix.feature-set }}"
          cargo test --features "${{ matrix.feature-set }}"

  doc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust (stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile Rust documentation
        run: cargo +stable doc --no-deps

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust with rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Run rustfmt
        run: cargo +stable fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust with clippy
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Run clippy
        run: cargo +stable clippy --all-targets --all-features -- -D warnings

  # ---------- WebAssembly target ----------
  wasm-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-set: [ default, missing_auto_plugin_is_compile_error, legacy_path_param, inventory ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust with wasm target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown   # installs the target via rustup

      - name: Verify crate for wasm32
        run: |
          echo "Building/tests (compile-only) for wasm32 with features: ${{ matrix.feature-set }}"
          cargo test --target wasm32-unknown-unknown --no-run --features "${{ matrix.feature-set }}"
          # To run the tests instead of just compiling, replace the line above with:
          # wasm-pack test --node --features "${{ matrix.feature-set }}"
