name: CI

on:
    # Trigger the workflow on push and pull requests to the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: --deny warnings
    RUSTDOCFLAGS: --deny warnings

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain: [stable]
                feature-set: [default, missing_auto_plugin_is_compile_error]
        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3
            
            # Install Rust for the selected toolchain
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}
                  override: true
            
            # Run tests with the specified feature set
            - name: Run tests
              if: ${{ matrix.toolchain == 'stable' || matrix.toolchain == 'nightly' }}
              run: |
                  echo "Testing with ${{ matrix.toolchain }} and features: ${{ matrix.toolchain }},${{ matrix.feature-set }}"
                  cargo test --features "${{ matrix.toolchain }},${{ matrix.feature-set }}"

    doc-test:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            -   name: Checkout code
                uses: actions/checkout@v3
            
            # Install Rust with stable toolchain
            -   name: Install Rust (stable)
                uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true
            
            # Compile documentation with stable
            -   name: Compile Rust documentation
                run: |
                    echo "Compiling Rust documentation"
                    cargo +stable doc --features=stable --no-deps

    rustfmt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Install Rust (stable)
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Install rustfmt
              run: |
                  echo "Installing rustfmt for stable"
                  rustup component add rustfmt --toolchain stable
    
            - name: Run rustfmt
              run: |
                  echo "Checking code formatting with rustfmt (stable)"
                  cargo +stable fmt --all -- --check

    clippy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Rust (stable)
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Install clippy
              run: |
                  echo "Installing clippy for stable"
                  rustup component add clippy --toolchain stable

            - name: Run clippy
              run: |
                  echo "Running clippy for lint checks (stable)"
                  cargo +stable clippy --all-targets --all-features -- -D warnings