name: CI

on:
    # Trigger the workflow on push and pull requests to the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: --deny warnings
    RUSTDOCFLAGS: --deny warnings

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain: [stable, nightly]
                feature-set: [default, missing_auto_plugin_is_compile_error]
        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3
            
            # Install Rust for the selected toolchain
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}
                  override: true
            
            # Run tests with the specified feature set
            - name: Run tests
              if: ${{ matrix.toolchain == 'nightly' || matrix.feature-set == 'default' }}
              run: |
                  echo "Testing with ${{ matrix.toolchain }} and features: ${{ matrix.toolchain }},${{ matrix.feature-set }}"
                  cargo test --features "${{ matrix.toolchain }},${{ matrix.feature-set }}"